import os
print(os.getenv('*'))
WEBRECON_RECORD_MODE=os.getenv('WEBRECON_RECORD_MODE')
WEBRECON_INDEX_URL=os.getenv('WEBRECON_INDEX_URL')
WEBRECON_RECORD_INDEX_NAME=os.getenv('WEBRECON_RECORD_INDEX_NAME')
