version: '3.1'
services:
  bot:
    image: allpps/web-recon:latest
    # build: web_recon
    command:
      - ruby
      - /usr/src/app/run_bot.rb
    env_file:
      .env
    environment:
      - APP_DIR=/usr/src/app
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LOG_DIR=/usr/src/app/logs
      - LOG_PATH=/usr/src/app/logs/log
      - LOG_LEVEL=DEBUG
      - QUEUE_URL=https://sqs.us-west-2.amazonaws.com/088617881078/web-recon
      - RESULTS_DIR=smash-crawl-results
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    volumes:
      - bundle_cache:/bundle
      - ./web_recon:/usr/src/app
    stdin_open: true
    tty: true
  selenium:
    image: selenium/standalone-chrome-debug:3.0.1-germanium
    logging:
      driver: none
    stdin_open: true
    tty: true
    volumes:
      - /dev/shm:/dev/shm
volumes:
  bundle_cache:
