version: '3.1'

services:
  bot:
    # image: allpps/web-recon
    build: crawl
    command:
      - ruby
      - /usr/src/app/run_bot.rb
      - https://www.skis.com/
    environment:
      - APP_DIR=/usr/src/app
      - HOST=web
      - LOG_DIR=/usr/src/app/logs
      - LOG_PATH=/usr/src/app/logs/log
      - LOG_LEVEL=DEBUG
      - QUEUE_URL=https://us-west-2.queue.amazonaws.com/088617881078/web-recon
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    volumes:
      - bundle_cache:/bundle
      - ./crawl:/usr/src/app
    stdin_open: true
    tty: true
  selenium:
    image: selenium/standalone-chrome-debug:3.0.1-germanium
    # logging:
    #   driver: none
    stdin_open: true
    tty: true
    volumes:
      - /dev/shm:/dev/shm

volumes:
  bundle_cache: