apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: recon-db-deployment
  labels:
    app: recon-db
spec:
  selector:
    matchLabels:
      app: recon-db
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: recon-db
    spec:
      containers:
      - name: recon-db
        image: amazon/dynamodb-local:latest
        ports:
        - containerPort: 4444
