source 'https://rubygems.org'
ruby '2.5.1'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'addressable' # (2.5.2)
gem 'capybara' # (3.8.0)
gem 'capybara-selenium'
gem 'childprocess' # (0.9.0)
gem 'chromedriver-helper'
gem 'ffi' # (1.9.25)
gem 'public_suffix' # (3.0.3)
gem 'mini_mime' # (1.0.1)
gem 'mini_portile2' # (2.3.0)
gem 'nokogiri' # (1.8.4)
gem 'rack' # (2.0.5)
gem 'rack-test' # (1.1.0)
gem 'rubyzip' #  (1.2.2)
gem 'selenium-webdriver' # (3.14.0)
gem 'xpath' # (3.1.0)
